### ISSUE TITLE
missing stable release on dockerhub (2.3.X)

### ISSUE THREAD

**Issue by hudecof** [instrumentisto/dovecot-docker-image#5]
Hi,

please could you update the containers on docker hub by adding tags for the 2.3.X releases?

  thanks
     Peter

**Comment by tyranron** [comment]
@hudecof there is still some work to be done before releasing those images. While they may be used, they are not considered to be production ready.

We have our own plan to upgrade this image and it includes producing a Docker image for every single version released starting from 2.2.27.0 and up until latest.

Also, we cannot give any ETAs about implementing this. We are sorry to say that, but at the time you'd better implement these changes in your own fork and produce your own Docker image.
